# Generated by Django 5.0.6 on 2024-06-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_segun', '0004_remove_carrocompra_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrocompra',
            name='productos',
            field=models.ManyToManyField(through='uni_segun.ProductoEnCarro', to='uni_segun.producto'),
        ),
    ]
